/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */







int BOUND  =    1000;
int m_Protocol  =    1;
int m_msg_2  =    2;
int m_recv_ack_2  =    3;
int m_msg_1_1  =    4;
int m_msg_1_2  =    5;
int m_recv_ack_1_1  =    6;
int m_recv_ack_1_2  =    7;
int kappa  =    0;

int main(void) 
{ int dummy ;
  int q ;
  int FLAG ;
  int i ;
  int method_id ;
  int this_expect ;
  int this_buffer_empty ;
  int symb[32] ;
  int P1 ;
  int P2 ;
  int P3 ;
  int P4 ;
  int P5 ;
  int P6 ;
  int P7 ;
  int P8 ;
  int P9 ;
  int FLAG___0 ;

  {
  dummy = 1;
  q = 0;
  FLAG = 0;
  i = 0;
  this_expect = 0;
  this_buffer_empty = 0;
  FLAG___0 = 0;
  while (FLAG___0 < BOUND) {
    klee_make_symbolic(symb, sizeof(int ) * 32U, "symb");
    P1 = nondet_int(); __CPROVER_input("P1",P1);
    P2 = nondet_int(); __CPROVER_input("P2",P2);
    P3 = nondet_int(); __CPROVER_input("P3",P3);
    P4 = nondet_int(); __CPROVER_input("P4",P4);
    P5 = nondet_int(); __CPROVER_input("P5",P5);
    P6 = nondet_int(); __CPROVER_input("P6",P6);
    P7 = nondet_int(); __CPROVER_input("P7",P7);
    P8 = nondet_int(); __CPROVER_input("P8",P8);
    P9 = nondet_int(); __CPROVER_input("P9",P9);
    if (q == 0) {
      if (symb[1]) {
        if (dummy == 1) {
          method_id = 1;
          if (dummy != 1) {
            goto POINT;
          }
          q = 1;
          this_expect = 0;
          this_buffer_empty = 1;
        }
        goto __Cont;
      }
      goto __Cont;
    }
    if (q == 1) {
      if (symb[2]) {
        if (! (P1 % 2 != 0)) {
          method_id = 2;
          if (P1 % 2 != this_expect % 2) {
            if (this_buffer_empty == 1) {
              if (! (P1 % 2 != 0)) {
                goto POINT;
              } else {
                goto _L___0;
              }
            } else {
              goto _L___0;
            }
          } else {
            _L___0: /* CIL Label */ 
            if (this_buffer_empty != 1) {
              if (! (P1 % 2 != 0)) {
                goto POINT;
              }
            }
          }
          q = 3;
          this_expect = this_expect + 1;
          this_buffer_empty = 1 - this_buffer_empty;
        }
        goto __Cont;
      }
      if (symb[3]) {
        if (! (P1 != 0)) {
          method_id = 3;
          if (P3 == (this_expect - 1) % 2) {
            if (this_buffer_empty != 1) {
              if (! (P3 != 0)) {
                goto POINT;
              }
            }
          }
          q = 2;
          break;
        }
        goto __Cont;
      }
      if (symb[4]) {
        if (P1 % 2 != 0) {
          if (P1 % 2 != 1) {
            if (P1 % 2 != 0) {
              method_id = 4;
              if (P4 % 2 == this_expect % 2) {
                if (this_buffer_empty == 1) {
                  if (P4 % 2 != 0) {
                    if (P4 % 2 != 0) {
                      if (P4 % 2 != 1) {
                        if (P4 % 2 != 0) {
                          goto POINT;
                        }
                      }
                    }
                  }
                }
              }
              q = 2;
              break;
            }
          }
        }
        goto __Cont;
      }
      if (symb[5]) {
        if (P1 % 2 != 0) {
          if (P1 % 2 != 1) {
            if (! (P1 % 2 != 0)) {
              goto _L___1;
            }
          } else {
            _L___1: /* CIL Label */ 
            method_id = 5;
            if (P6 % 2 == this_expect % 2) {
              if (this_buffer_empty == 1) {
                if (P6 % 2 != 0) {
                  if (P6 % 2 != 0) {
                    if (P6 % 2 != 1) {
                      if (! (P6 % 2 != 0)) {
                        goto POINT;
                      }
                    } else {
                      goto POINT;
                    }
                  }
                }
              }
            }
            q = 2;
            break;
          }
        }
        goto __Cont;
      }
      if (symb[6]) {
        if (P1 != 0) {
          if (P1 != 1) {
            if (P1 != 0) {
              method_id = 6;
              if (P8 == (this_expect - 1) % 2) {
                if (this_buffer_empty != 1) {
                  if (P8 != 0) {
                    if (P8 != 0) {
                      if (P8 != 1) {
                        if (P8 != 0) {
                          goto POINT;
                        }
                      }
                    }
                  }
                }
              }
              q = 2;
              break;
            }
          }
        }
        goto __Cont;
      }
      if (symb[7]) {
        if (P1 != 0) {
          if (P1 != 1) {
            if (! (P1 != 0)) {
              goto _L___2;
            }
          } else {
            _L___2: /* CIL Label */ 
            method_id = 7;
            if (P9 == (this_expect - 1) % 2) {
              if (this_buffer_empty != 1) {
                if (P9 != 0) {
                  if (P9 != 0) {
                    if (P9 != 1) {
                      if (! (P9 != 0)) {
                        goto POINT;
                      }
                    } else {
                      goto POINT;
                    }
                  }
                }
              }
            }
            q = 2;
            break;
          }
        }
        goto __Cont;
      }
      goto __Cont;
    }
    if (q == 2) {
      if (symb[8]) {
        if (! (P1 % 2 != 0)) {
          method_id = 2;
          if (P1 % 2 == this_expect % 2) {
            if (this_buffer_empty == 1) {
              if (! (P1 % 2 != 0)) {
                goto POINT;
              }
            }
          }
          q = 2;
          break;
        }
        goto __Cont;
      }
      if (symb[9]) {
        if (! (P1 != 0)) {
          method_id = 3;
          if (P3 == (this_expect - 1) % 2) {
            if (this_buffer_empty != 1) {
              if (! (P3 != 0)) {
                goto POINT;
              }
            }
          }
          q = 2;
          break;
        }
        goto __Cont;
      }
      if (symb[10]) {
        if (P1 % 2 != 0) {
          if (P1 % 2 != 1) {
            if (P1 % 2 != 0) {
              method_id = 4;
              if (P4 % 2 == this_expect % 2) {
                if (this_buffer_empty == 1) {
                  if (P4 % 2 != 0) {
                    if (P4 % 2 != 0) {
                      if (P4 % 2 != 1) {
                        if (P4 % 2 != 0) {
                          goto POINT;
                        }
                      }
                    }
                  }
                }
              }
              q = 2;
              break;
            }
          }
        }
        goto __Cont;
      }
      if (symb[11]) {
        if (P1 % 2 != 0) {
          if (P1 % 2 != 1) {
            if (! (P1 % 2 != 0)) {
              goto _L___3;
            }
          } else {
            _L___3: /* CIL Label */ 
            method_id = 5;
            if (P6 % 2 == this_expect % 2) {
              if (this_buffer_empty == 1) {
                if (P6 % 2 != 0) {
                  if (P6 % 2 != 0) {
                    if (P6 % 2 != 1) {
                      if (! (P6 % 2 != 0)) {
                        goto POINT;
                      }
                    } else {
                      goto POINT;
                    }
                  }
                }
              }
            }
            q = 2;
            break;
          }
        }
        goto __Cont;
      }
      if (symb[12]) {
        if (P1 != 0) {
          if (P1 != 1) {
            if (P1 != 0) {
              method_id = 6;
              if (P8 == (this_expect - 1) % 2) {
                if (this_buffer_empty != 1) {
                  if (P8 != 0) {
                    if (P8 != 0) {
                      if (P8 != 1) {
                        if (P8 != 0) {
                          goto POINT;
                        }
                      }
                    }
                  }
                }
              }
              q = 2;
              break;
            }
          }
        }
        goto __Cont;
      }
      if (symb[13]) {
        if (P1 != 0) {
          if (P1 != 1) {
            if (! (P1 != 0)) {
              goto _L___4;
            }
          } else {
            _L___4: /* CIL Label */ 
            method_id = 7;
            if (P9 == (this_expect - 1) % 2) {
              if (this_buffer_empty != 1) {
                if (P9 != 0) {
                  if (P9 != 0) {
                    if (P9 != 1) {
                      if (! (P9 != 0)) {
                        goto POINT;
                      }
                    } else {
                      goto POINT;
                    }
                  }
                }
              }
            }
            q = 2;
            break;
          }
        }
        goto __Cont;
      }
      goto __Cont;
    }
    if (q == 3) {
      if (symb[14]) {
        if (! (P1 % 2 != 0)) {
          method_id = 2;
          if (P1 % 2 == this_expect % 2) {
            if (this_buffer_empty == 1) {
              if (! (P1 % 2 != 0)) {
                goto POINT;
              }
            }
          }
          q = 2;
          break;
        }
        goto __Cont;
      }
      if (symb[15]) {
        if (! (P1 != 0)) {
          method_id = 3;
          if (this_buffer_empty == 1) {
            if (! (P3 != 0)) {
              goto POINT;
            } else {
              goto _L___5;
            }
          } else {
            _L___5: /* CIL Label */ 
            if (P3 != (this_expect - 1) % 2) {
              if (this_buffer_empty != 1) {
                if (! (P3 != 0)) {
                  goto POINT;
                }
              }
            }
          }
          q = 4;
          this_expect = this_expect;
          this_buffer_empty = 1 - this_buffer_empty;
        }
        goto __Cont;
      }
      if (symb[16]) {
        if (P1 % 2 != 0) {
          if (P1 % 2 != 1) {
            if (P1 % 2 != 0) {
              method_id = 4;
              if (P4 % 2 == this_expect % 2) {
                if (this_buffer_empty == 1) {
                  if (P4 % 2 != 0) {
                    if (P4 % 2 != 0) {
                      if (P4 % 2 != 1) {
                        if (P4 % 2 != 0) {
                          goto POINT;
                        }
                      }
                    }
                  }
                }
              }
              q = 2;
              break;
            }
          }
        }
        goto __Cont;
      }
      if (symb[17]) {
        if (P1 % 2 != 0) {
          if (P1 % 2 != 1) {
            if (! (P1 % 2 != 0)) {
              goto _L___6;
            }
          } else {
            _L___6: /* CIL Label */ 
            method_id = 5;
            if (P6 % 2 == this_expect % 2) {
              if (this_buffer_empty == 1) {
                if (P6 % 2 != 0) {
                  if (P6 % 2 != 0) {
                    if (P6 % 2 != 1) {
                      if (! (P6 % 2 != 0)) {
                        goto POINT;
                      }
                    } else {
                      goto POINT;
                    }
                  }
                }
              }
            }
            q = 2;
            break;
          }
        }
        goto __Cont;
      }
      if (symb[18]) {
        if (P1 != 0) {
          if (P1 != 1) {
            if (P1 != 0) {
              method_id = 6;
              if (P8 == (this_expect - 1) % 2) {
                if (this_buffer_empty != 1) {
                  if (P8 != 0) {
                    if (P8 != 0) {
                      if (P8 != 1) {
                        if (P8 != 0) {
                          goto POINT;
                        }
                      }
                    }
                  }
                }
              }
              q = 2;
              break;
            }
          }
        }
        goto __Cont;
      }
      if (symb[19]) {
        if (P1 != 0) {
          if (P1 != 1) {
            if (! (P1 != 0)) {
              goto _L___7;
            }
          } else {
            _L___7: /* CIL Label */ 
            method_id = 7;
            if (P9 == (this_expect - 1) % 2) {
              if (this_buffer_empty != 1) {
                if (P9 != 0) {
                  if (P9 != 0) {
                    if (P9 != 1) {
                      if (! (P9 != 0)) {
                        goto POINT;
                      }
                    } else {
                      goto POINT;
                    }
                  }
                }
              }
            }
            q = 2;
            break;
          }
        }
        goto __Cont;
      }
      goto __Cont;
    }
    if (q == 4) {
      if (symb[20]) {
        if (! (P1 % 2 != 0)) {
          method_id = 2;
          if (P1 % 2 == this_expect % 2) {
            if (this_buffer_empty == 1) {
              if (! (P1 % 2 != 0)) {
                goto POINT;
              }
            }
          }
          q = 2;
          break;
        }
        goto __Cont;
      }
      if (symb[21]) {
        if (! (P1 != 0)) {
          method_id = 3;
          if (P3 == (this_expect - 1) % 2) {
            if (this_buffer_empty != 1) {
              if (! (P3 != 0)) {
                goto POINT;
              }
            }
          }
          q = 2;
          break;
        }
        goto __Cont;
      }
      if (symb[22]) {
        if (P1 % 2 != 0) {
          if (P1 % 2 != 1) {
            if (P1 % 2 != 0) {
              method_id = 4;
              if (P4 % 2 == this_expect % 2) {
                if (this_buffer_empty == 1) {
                  if (P4 % 2 != 0) {
                    if (P4 % 2 != 0) {
                      if (P4 % 2 != 1) {
                        if (P4 % 2 != 0) {
                          goto POINT;
                        }
                      }
                    }
                  }
                }
              }
              q = 2;
              break;
            }
          }
        }
        goto __Cont;
      }
      if (symb[23]) {
        if (P1 % 2 != 0) {
          if (P1 % 2 != 1) {
            if (! (P1 % 2 != 0)) {
              goto _L___11;
            }
          } else {
            _L___11: /* CIL Label */ 
            method_id = 5;
            if (P6 % 2 != this_expect % 2) {
              if (this_buffer_empty == 1) {
                if (P6 % 2 != 0) {
                  if (P6 % 2 != 0) {
                    if (P6 % 2 != 1) {
                      if (P6 % 2 != 0) {
                        goto _L___10;
                      } else {
                        goto POINT;
                      }
                    } else {
                      goto POINT;
                    }
                  } else {
                    goto _L___10;
                  }
                } else {
                  goto _L___10;
                }
              } else {
                goto _L___10;
              }
            } else {
              _L___10: /* CIL Label */ 
              if (this_buffer_empty != 1) {
                if (P6 % 2 != 0) {
                  if (P6 % 2 != 0) {
                    if (P6 % 2 != 1) {
                      if (! (P6 % 2 != 0)) {
                        goto POINT;
                      }
                    } else {
                      goto POINT;
                    }
                  }
                }
              }
            }
            q = 5;
            this_expect = this_expect + 1;
            this_buffer_empty = 1 - this_buffer_empty;
          }
        }
        goto __Cont;
      }
      if (symb[24]) {
        if (P1 != 0) {
          if (P1 != 1) {
            if (P1 != 0) {
              method_id = 6;
              if (P8 == (this_expect - 1) % 2) {
                if (this_buffer_empty != 1) {
                  if (P8 != 0) {
                    if (P8 != 0) {
                      if (P8 != 1) {
                        if (P8 != 0) {
                          goto POINT;
                        }
                      }
                    }
                  }
                }
              }
              q = 2;
              break;
            }
          }
        }
        goto __Cont;
      }
      if (symb[25]) {
        if (P1 != 0) {
          if (P1 != 1) {
            if (! (P1 != 0)) {
              goto _L___12;
            }
          } else {
            _L___12: /* CIL Label */ 
            method_id = 7;
            if (P9 == (this_expect - 1) % 2) {
              if (this_buffer_empty != 1) {
                if (P9 != 0) {
                  if (P9 != 0) {
                    if (P9 != 1) {
                      if (! (P9 != 0)) {
                        goto POINT;
                      }
                    } else {
                      goto POINT;
                    }
                  }
                }
              }
            }
            q = 2;
            break;
          }
        }
        goto __Cont;
      }
      goto __Cont;
    }
    if (q == 5) {
      if (symb[26]) {
        if (! (P1 % 2 != 0)) {
          method_id = 2;
          if (P1 % 2 == this_expect % 2) {
            if (this_buffer_empty == 1) {
              if (! (P1 % 2 != 0)) {
                goto POINT;
              }
            }
          }
          q = 2;
          break;
        }
        goto __Cont;
      }
      if (symb[27]) {
        if (! (P1 != 0)) {
          method_id = 3;
          if (P3 == (this_expect - 1) % 2) {
            if (this_buffer_empty != 1) {
              if (! (P3 != 0)) {
                goto POINT;
              }
            }
          }
          q = 2;
          break;
        }
        goto __Cont;
      }
      if (symb[28]) {
        if (P1 % 2 != 0) {
          if (P1 % 2 != 1) {
            if (P1 % 2 != 0) {
              method_id = 4;
              if (P4 % 2 == this_expect % 2) {
                if (this_buffer_empty == 1) {
                  if (P4 % 2 != 0) {
                    if (P4 % 2 != 0) {
                      if (P4 % 2 != 1) {
                        if (P4 % 2 != 0) {
                          goto POINT;
                        }
                      }
                    }
                  }
                }
              }
              q = 2;
              break;
            }
          }
        }
        goto __Cont;
      }
      if (symb[29]) {
        if (P1 % 2 != 0) {
          if (P1 % 2 != 1) {
            if (! (P1 % 2 != 0)) {
              goto _L___13;
            }
          } else {
            _L___13: /* CIL Label */ 
            method_id = 5;
            if (P6 % 2 == this_expect % 2) {
              if (this_buffer_empty == 1) {
                if (P6 % 2 != 0) {
                  if (P6 % 2 != 0) {
                    if (P6 % 2 != 1) {
                      if (! (P6 % 2 != 0)) {
                        goto POINT;
                      }
                    } else {
                      goto POINT;
                    }
                  }
                }
              }
            }
            q = 2;
            break;
          }
        }
        goto __Cont;
      }
      if (symb[30]) {
        if (P1 != 0) {
          if (P1 != 1) {
            if (P1 != 0) {
              method_id = 6;
              if (P8 == (this_expect - 1) % 2) {
                if (this_buffer_empty != 1) {
                  if (P8 != 0) {
                    if (P8 != 0) {
                      if (P8 != 1) {
                        if (P8 != 0) {
                          goto POINT;
                        }
                      }
                    }
                  }
                }
              }
              q = 2;
              break;
            }
          }
        }
        goto __Cont;
      }
      if (symb[31]) {
        if (P1 != 0) {
          if (P1 != 1) {
            if (! (P1 != 0)) {
              goto _L___16;
            }
          } else {
            _L___16: /* CIL Label */ 
            method_id = 7;
            if (this_buffer_empty == 1) {
              if (P9 != 0) {
                if (P9 != 0) {
                  if (P9 != 1) {
                    if (P9 != 0) {
                      goto _L___15;
                    } else {
                      goto POINT;
                    }
                  } else {
                    goto POINT;
                  }
                } else {
                  goto _L___15;
                }
              } else {
                goto _L___15;
              }
            } else {
              _L___15: /* CIL Label */ 
              if (P9 != (this_expect - 1) % 2) {
                if (this_buffer_empty != 1) {
                  if (P9 != 0) {
                    if (P9 != 0) {
                      if (P9 != 1) {
                        if (! (P9 != 0)) {
                          goto POINT;
                        }
                      } else {
                        goto POINT;
                      }
                    }
                  }
                }
              }
            }
            q = 1;
            this_expect = this_expect;
            this_buffer_empty = 1 - this_buffer_empty;
          }
        }
        goto __Cont;
      }
      goto __Cont;
    }
    __Cont: /* CIL Label */ 
    FLAG___0 = FLAG___0 + 1;
  }
  POINT: 

  return (0);
}
}
