/* Generated by CIL v. 1.3.7 */
/* print_CIL_Input is true */







int BOUND  =    500;
int m_isPowerOfTwo  =    1;
int m_IntMath  =    2;
int m_log10  =    3;
int m_checkedSubtract  =    4;
int m_checkedMultiply  =    5;
int m_log2  =    6;
int m_checkedAdd  =    7;
int m_mod_1  =    8;
int m_mod_2  =    9;
int m_factorial_1  =    10;
int m_factorial_2  =    11;
int kappa  =    0;
int main(void) 
{ int dummy ;
  int q ;
  int FLAG ;
  int i ;
  int method_id ;
  int symb[20] ;
  int P1 ;
  int P2 ;
  int P3 ;
  int P4 ;
  int P5 ;
  int P6 ;
  int P7 ;
  int P8 ;
  int P9 ;
  int P10 ;
  int P11 ;
  int P12 ;
  int P13 ;
  int P14 ;
  int P15 ;
  int P16 ;
  int P17 ;
  int FLAG___0 ;

  {
  dummy = 1;
  q = 0;
  FLAG = 0;
  i = 0;
  FLAG___0 = 0;
  while (FLAG___0 < BOUND) {
    klee_make_symbolic(symb, sizeof(int ) * 20U, "symb");
    P1 = nondet_int(); __CPROVER_input("P1",P1);
    P2 = nondet_int(); __CPROVER_input("P2",P2);
    P3 = nondet_int(); __CPROVER_input("P3",P3);
    P4 = nondet_int(); __CPROVER_input("P4",P4);
    P5 = nondet_int(); __CPROVER_input("P5",P5);
    P6 = nondet_int(); __CPROVER_input("P6",P6);
    P7 = nondet_int(); __CPROVER_input("P7",P7);
    P8 = nondet_int(); __CPROVER_input("P8",P8);
    P9 = nondet_int(); __CPROVER_input("P9",P9);
    P10 = nondet_int(); __CPROVER_input("P10",P10);
    P11 = nondet_int(); __CPROVER_input("P11",P11);
    P12 = nondet_int(); __CPROVER_input("P12",P12);
    P13 = nondet_int(); __CPROVER_input("P13",P13);
    P14 = nondet_int(); __CPROVER_input("P14",P14);
    P15 = nondet_int(); __CPROVER_input("P15",P15);
    P16 = nondet_int(); __CPROVER_input("P16",P16);
    P17 = nondet_int(); __CPROVER_input("P17",P17);
    if (q == 0) {
      if (symb[1]) {
        if (dummy == 1) {
          method_id = 2;
          if (dummy != 1) {
            goto POINT;
          }
          q = 2;
        }
        goto __Cont;
      }
      goto __Cont;
    }
    if (q == 1) {
      if (symb[2]) {
        if (dummy == 1) {
          method_id = 3;
          if (dummy != 1) {
            goto POINT;
          }
          q = 1;
          break;
        }
        goto __Cont;
      }
      if (symb[3]) {
        if (dummy == 1) {
          method_id = 6;
          if (dummy != 1) {
            goto POINT;
          }
          q = 1;
          break;
        }
        goto __Cont;
      }
      if (symb[4]) {
        if (P1 >= 0) {
          if (! (P2 > 0)) {
            goto _L;
          }
        } else {
          _L: /* CIL Label */ 
          method_id = 9;
          if (dummy != 1) {
            goto POINT;
          }
          q = 1;
          break;
        }
        goto __Cont;
      }
      if (symb[5]) {
        if (P1 < 0) {
          method_id = 10;
          if (dummy != 1) {
            goto POINT;
          }
          q = 1;
          break;
        }
        goto __Cont;
      }
      goto __Cont;
    }
    if (q == 2) {
      if (symb[6]) {
        if (dummy == 1) {
          if ((P1 & (P1 - 1)) == 0) {
            if (P1 > 0) {
              goto _L___0;
            } else {
              goto _L___1;
            }
          } else {
            _L___1: /* CIL Label */ 
            if (dummy != 1) {
              _L___0: /* CIL Label */ 
              method_id = 1;
              if (dummy != 1) {
                goto POINT;
              }
              q = 2;
            }
          }
        }
        goto __Cont;
      }
      if (symb[7]) {
        if (dummy == 1) {
          if ((P1 & (P1 - 1)) == 0) {
            if (P1 > 0) {
              goto _L___4;
            } else {
              goto _L___5;
            }
          } else {
            _L___5: /* CIL Label */ 
            if (dummy != 1) {
              _L___4: /* CIL Label */ 
              if ((P1 & (P1 - 1)) != 0) {
                if (P1 > 0) {
                  goto _L___2;
                } else {
                  goto _L___3;
                }
              } else {
                _L___3: /* CIL Label */ 
                if (dummy != 1) {
                  _L___2: /* CIL Label */ 
                  method_id = 1;
                  if (dummy != 1) {
                    goto POINT;
                  }
                  q = 2;
                }
              }
            }
          }
        }
        goto __Cont;
      }
      if (symb[8]) {
        if (dummy == 1) {
          if ((P1 & (P1 - 1)) == 0) {
            if (P1 > 0) {
              goto _L___10;
            } else {
              goto _L___11;
            }
          } else {
            _L___11: /* CIL Label */ 
            if (dummy != 1) {
              _L___10: /* CIL Label */ 
              if ((P1 & (P1 - 1)) != 0) {
                if (P1 > 0) {
                  goto _L___8;
                } else {
                  goto _L___9;
                }
              } else {
                _L___9: /* CIL Label */ 
                if (dummy != 1) {
                  _L___8: /* CIL Label */ 
                  if ((P1 & (P1 - 1)) == 0) {
                    if (P1 <= 0) {
                      goto _L___6;
                    } else {
                      goto _L___7;
                    }
                  } else {
                    _L___7: /* CIL Label */ 
                    if (dummy != 1) {
                      _L___6: /* CIL Label */ 
                      method_id = 1;
                      if (dummy != 1) {
                        goto POINT;
                      }
                      q = 2;
                    }
                  }
                }
              }
            }
          }
        }
        goto __Cont;
      }
      if (symb[9]) {
        if (dummy == 1) {
          if ((P1 & (P1 - 1)) == 0) {
            if (P1 > 0) {
              goto _L___18;
            } else {
              goto _L___19;
            }
          } else {
            _L___19: /* CIL Label */ 
            if (dummy != 1) {
              _L___18: /* CIL Label */ 
              if ((P1 & (P1 - 1)) != 0) {
                if (P1 > 0) {
                  goto _L___16;
                } else {
                  goto _L___17;
                }
              } else {
                _L___17: /* CIL Label */ 
                if (dummy != 1) {
                  _L___16: /* CIL Label */ 
                  if ((P1 & (P1 - 1)) == 0) {
                    if (P1 <= 0) {
                      goto _L___14;
                    } else {
                      goto _L___15;
                    }
                  } else {
                    _L___15: /* CIL Label */ 
                    if (dummy != 1) {
                      _L___14: /* CIL Label */ 
                      if ((P1 & (P1 - 1)) != 0) {
                        if (P1 <= 0) {
                          goto _L___12;
                        } else {
                          goto _L___13;
                        }
                      } else {
                        _L___13: /* CIL Label */ 
                        if (dummy != 1) {
                          _L___12: /* CIL Label */ 
                          method_id = 1;
                          if (dummy != 1) {
                            goto POINT;
                          }
                          q = 2;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        goto __Cont;
      }
      if (symb[10]) {
        if (dummy == 1) {
          method_id = 3;
          if (dummy != 1) {
            goto POINT;
          }
          q = 1;
          break;
        }
        goto __Cont;
      }
      if (symb[11]) {
        if (dummy == 1) {
          method_id = 4;
          if (dummy != 1) {
            goto POINT;
          }
          q = 2;
        }
        goto __Cont;
      }
      if (symb[12]) {
        if (dummy == 1) {
          method_id = 5;
          if (dummy != 1) {
            goto POINT;
          }
          q = 2;
        }
        goto __Cont;
      }
      if (symb[13]) {
        if (dummy == 1) {
          method_id = 6;
          if (dummy != 1) {
            goto POINT;
          }
          q = 1;
          break;
        }
        goto __Cont;
      }
      if (symb[14]) {
        if (dummy == 1) {
          method_id = 7;
          if (dummy != 1) {
            goto POINT;
          }
          q = 2;
        }
        goto __Cont;
      }
      if (symb[15]) {
        if (P1 >= 0) {
          if (P2 > 0) {
            method_id = 8;
            if (dummy != 1) {
              goto POINT;
            }
            q = 2;
          }
        }
        goto __Cont;
      }
      if (symb[16]) {
        if (P1 >= 0) {
          if (! (P2 > 0)) {
            goto _L___20;
          }
        } else {
          _L___20: /* CIL Label */ 
          method_id = 9;
          if (dummy != 1) {
            goto POINT;
          }
          q = 1;
          break;
        }
        goto __Cont;
      }
      if (symb[17]) {
        if (P1 < 0) {
          method_id = 10;
          if (dummy != 1) {
            goto POINT;
          }
          q = 1;
          break;
        }
        goto __Cont;
      }
      if (symb[18]) {
        if (! (P1 < 0)) {
          if (P17 < 13) {
            if (P17 >= 0) {
              goto _L___21;
            } else {
              goto _L___22;
            }
          } else {
            _L___22: /* CIL Label */ 
            if (dummy != 1) {
              _L___21: /* CIL Label */ 
              method_id = 11;
              if (dummy != 1) {
                goto POINT;
              }
              q = 2;
            }
          }
        }
        goto __Cont;
      }
      if (symb[19]) {
        if (! (P1 < 0)) {
          if (P17 < 13) {
            if (P17 >= 0) {
              goto _L___25;
            } else {
              goto _L___26;
            }
          } else {
            _L___26: /* CIL Label */ 
            if (dummy != 1) {
              _L___25: /* CIL Label */ 
              if (P17 >= 13) {
                if (P17 >= 0) {
                  goto _L___23;
                } else {
                  goto _L___24;
                }
              } else {
                _L___24: /* CIL Label */ 
                if (dummy != 1) {
                  _L___23: /* CIL Label */ 
                  method_id = 11;
                  if (dummy != 1) {
                    goto POINT;
                  }
                  q = 2;
                }
              }
            }
          }
        }
        goto __Cont;
      }
      goto __Cont;
    }
    __Cont: /* CIL Label */ 
    FLAG___0 = FLAG___0 + 1;
  }
  POINT: 
  return (0);
}
}
